//Login
export const LOGIN='LOGIN';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAILURE='LOGIN_FAILURE';

//Sign up
export const SIGNUP='SIGNUP';
export const SIGNUP_SUCCESS='SIGNUP_SUCCESS';
export const SIGNUP_FAILURE='SIGNUP_FAILURE';

//Imdb Movie Api
export const MOVIE_LIST='MOVIE_LIST';
export const MOVIE_LIST_SUCCESS='MOVIE_LIST_SUCCESS';
export const MOVIE_LIST_FAILURE='MOVIE_LIST_FAILURE';

export const TOP_RATED_MOVIE_LIST='TOP_RATED_MOVIE_LIST';
export const TOP_RATED_MOVIE_LIST_SUCCESS='TOP_RATED_MOVIE_LIST_SUCCESS';
export const TOP_RATED_MOVIE_LIST_FAILURE='TOP_RATED_MOVIE_LIST_FAILURE';

export const FETCH_POPULAR_MOVIE='FETCH_POPULAR_MOVIE';
export const FETCH_POPULAR_MOVIE_SUCCESS='FETCH_POPULAR_MOVIE_SUCCESS';
export const FETCH_POPULAR_MOVIE_FAILURE='FETCH_POPULAR_MOVIE_FAILURE';







